### PR TITLE
Remove redundant controller endpoint

### PR DESCRIPTION
**Pull request by ghjm**
Right now if you run `receptor controller`, the differences from `receptor node` are:
* The `--server-disable` option to suppress starting a listener is unavailable
* You cannot specify `--peer` options to make outbound connections
* You cannot specify a keepalive interval to send keepalives
* You can specify a `socket_path` option, but it doesn't actually do anything

Intuitively, you would expect that `receptor controller` is somehow a different mode of operation or does something that `receptor node` doesn't do, but this is not actually the case.

### CODE REVIEW

**Comment by elyezer** [comment]
Once this is merged I will basically need to replace `controller` with `node` for places I used to start as a controller. Is that correct?

If that is correct, then the perf tests will need to be updated since it starts receptor as controller.

**Comment by ghjm** [comment]
Yes, that is correct @elyezer.  If this PR is accepted, then everything that runs `receptor controller` will need to switch to `receptor node`.

I would put in an alias that makes the two strictly equivalent, but I can't see a reasonable way to do that with the way `config.py` is currently structured.

**Comment by elyezer** [comment]
@ghjm thanks for the clarification, I can work on updating the tests if this PR gets accepted.

**Review by matburt — APPROVED** [review]
The whole controller/node separation was really just part of an early design idea that fell away as the receptor architecture matured.

The intention is, primarily, for a controller to be some other tool that imports the receptor interface and acts as a distinct controller for a mesh in that particular role. Reality is that there is no "controller" beyond this. Everything is node.

**Comment by jhjaggars** [comment]
> Everything is node.

All hail Node!

**Review by jhjaggars — APPROVED** [review]

**Pull request merged**
