### PR TITLE
Check for invalid listener URLs

### PR DESCRIPTION
**Pull request by ghjm**
This PR verifies that the given URL for a Receptor peer does not include extraneous information such as a path, and also checks earlier that it matches one of the known schemes.  See https://github.com/project-receptor/receptor/issues/153.

### CODE REVIEW

**Review by matburt — CHANGES_REQUESTED** [review]
Would be good to have some tests for this, otherwise looks good

**Comment by jeremy-audet** [comment]
Does this mean that `--listen=receptor://127.0.0.1:8888` is now invalid?

**Comment by ghjm** [comment]
Oops, no, I didn't mean to remove `receptor://`.  I'll fix it.

**Comment by ghjm** [comment]
Actually, `receptor://` still works with this code as-is.  The string replace is done before we check the set of allowed schemes, so `receptor://` has already been translated to `rnp://` and passes the test.

**Review by matburt — APPROVED** [review]

**Pull request merged**
