### PR TITLE
Backport Graham's http proxy changes to the release_0.6 branch

### PR DESCRIPTION
**Pull request by dehort**

### CODE REVIEW

**Review by ghjm — APPROVED** [review]

**Comment by dehort** [comment]
recheck

**Comment by elyezer** [comment]
I was able to pull and verify these changes by doing what was done for the devel branch https://github.com/project-receptor/receptor/issues/191#issuecomment-631604051

That said these changes looks good to be merged.

**Comment by ghjm** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Pull request merged**
