### PR TITLE
Add test for invalid listen scheme

### PR DESCRIPTION
**Pull request by jeremy-audet**

### CODE REVIEW

**Comment by jeremy-audet** [comment]
This PR also originally included https://github.com/project-receptor/receptor/issues/93#issuecomment-587539937, but that test is currently failing, and it doesn't even assert correct behaviour, so it seems a bit odd to add right now.

**Comment by jeremy-audet** [comment]
<strike>The new test introduced by this PR is failing, and I don't know why. I can't reproduce the failure locally.</strike>

Quite a few tests are failing, and I _can_ reproduce locally, even without this PR. Very annoying.

**Comment by jeremy-audet** [comment]
Rebased and added a second commit which tests #138.

**Review by elyezer — APPROVED** [review]
LGTM

**Comment by jeremy-audet** [comment]
Rebased, and added tests for https://github.com/project-receptor/receptor/issues/153

**Comment by jeremy-audet** [comment]
BTW the automated tests added by this PR currently pass very consistently against devel. I don't recall the last time I've seen any of them fail, if ever.

**Comment by jeremy-audet** [comment]
Dropped the `_wait_for_conns` method added by the second commit, as https://github.com/project-receptor/affinity/pull/35 makes it unnecessary. Tests still pass against the devel branch.

**Review by matburt — APPROVED** [review]

**Pull request merged**
